apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: grafana-portal
spec:
  portal:
    registration:
      type: anonymous
  workshops:
  - name: grafana
    capacity: 1
    reserved: 0
    expires: 60m
    orphaned: 1m