apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: grafana
spec:
  vendor: Grafana Labs
  title: Grafana Stack
  description: MLTs with Grafana
  content:
    files: github.com/techgnosis/grafana-workshop
  duration: 60m
  session:
    namespaces:
      budget: small
    applications:
      docker:
        enabled: false
      terminal:
        enabled: false
      console:
        enabled: false
      editor:
        enabled: false